version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: splshield-telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - API_BASE_URL=http://splshield-api:8000
    networks:
      - pg-network
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  pg-network:
    external: true